name: Sync Changes

on:
  push:
    branches:
      - main

jobs:
  sync_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Second Repository
        uses: actions/checkout@v2

      - name: Sync Changes from First Repository
        run: |
          git config user.name "muram-105"
          git config user.email "muram8700@gmail.com"
          git pull Repo-3 main
          git push origin main
