name: Sync Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the original repository to a local directory
      - name: Checkout Original Repo
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo3
          ref: main
          path: original


