name: Sync Repos

# Run the workflow on push events to the main branch of the original repository
on:
  push:
    branches:
      - main
    paths:
      - 'path/to/repo3/**' # Replace with the actual path to the original repository

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the original repository to a local directory
      - name: Checkout Original Repo
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo3
          ref: main

      # Checkout the copy repository to a local directory
      - name: Checkout Copy Repo
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo4
          ref: main
          path: copy-repo

      # Sync changes from the original repository to the copy repository
      - name: Sync Repos
        run: |
          cd Repo3
          git remote add copy ../copy-repo 
          git pull copy main 
          git push origin main 
name: Sync Repos

# Run the workflow on push events to the main branch of the original repository
on:
  push:
    branches:
      - main
    paths:
      - 'path/to/repo3/**' # Replace with the actual path to the original repository

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the original repository to a local directory
      - name: Checkout Original Repo
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo3
          ref: main

      # Checkout the copy repository to a local directory
      - name: Checkout Copy Repo
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo4
          ref: main
          path: copy-repo

      # Sync changes from the original repository to the copy repository
      - name: Sync Repos
        run: |
          cd Repo3
          git remote add copy ../copy-repo 
          git pull copy main 
          git push origin main 
