name: Sync Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the original repository to a local directory
      - name: Checkout Original Repo
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo3
          ref: main
          path: original

      # Clone the original repository to a new directory
      - name: Clone Copied Repo
        run: |
          git clone --mirror original/ copied/
        working-directory: .

      # Sync changes from the original repository to the copied repository
      - name: Sync Repos
        run: |
          git -C original push --mirror copied.git
