name: Sync Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Create a new repository with the same content as Repo3
      - name: Create Repo4
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Initial commit"
          title: "Create Repo4"
          body: "This pull request creates a new repository with the same content as Repo3"
          branch: main
          branch-suffix: "-copy"
          delete-branch: true
          target: muram-105
          changes: |
            mkdir Repo4
            cd Repo4
            git init
            git remote add origin https://github.com/muram-105/Repo4.git
            git pull https://github.com/muram-105/Repo3.git main

      # Push changes to Repo4
      - name: Push to Repo4
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          directory: ./Repo4
