name: Set up script

on:
  push:
    branches:
      - main
# on:
#   schedule:
#     - cron: '0 0 * * *' # Run every day at midnight

jobs:
  set-up-script:
    runs-on: ubuntu-latest
    steps:
      - name: Set execute permission on sync script
        run: chmod +x sync-script.sh
        
        
      - name: Set up script
        run: |
          ls
          ./sync-script.sh
