name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout First Repository
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo3
          ref: main

      - name: Checkout Second Repository
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo4
          ref: main
          path: ../Repo4

      - name: Sync Repositories
        run: |
          git -C ../Repo4 remote add upstream ../Repo3
          git -C ../Repo4 pull upstream main --no-edit
          git -C ../Repo4 push origin main
