name: Sync Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the first repository to a local directory
      - name: Checkout First Repo
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo3
          ref: main
          path: Repo3

      # Checkout the second repository to a local directory
      - name: Checkout Second Repo
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo4
          ref: main
          path: Repo4

      # Sync changes from the first repository to the second repository
      - name: Sync Repos
        run: |
          cd repo1
          git remote add Repo4 ../Repo4
          git pull Repo4 main 
          git push origin main 
