name: Sync Repos

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo3
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo3
          ref: main
      
      - name: Checkout Repo4
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo4
          ref: main

      - name: Sync Repos
        run: |
          cd Repo4
          git pull origin main
          cd ../Repo3
          git add .
          git commit -m "Sync with Repo4"
          git push origin main
