name: Set up script

on:
  push:
    branches:
      - main

jobs:
  set-up-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo3
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo3
          ref: main

      - name: Set up script
        run: |
          ls
          ./sync-script.sh
