name: Set up script

on:
  push:
    branches:
      - main

jobs:
  set-up-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo3
        uses: actions/checkout@v2
        with:
          repository: muram-105/repo3
          ref: main

      - name: Install script dependencies
        run: |
          # Install dependencies for your script here

      - name: Set up script
        run: |
          ls
          cp -R repo3/* .
      - name: Commit and push changes to repo4
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Update contents from repo3"
          git push
