name: Set up script

on:
  push:
    branches:
      - main

jobs:
  set-up-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo3
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo4
          ref: main
      - name: Set execute permission on sync script
        run: chmod +x sync-script.sh
        
        
      - name: Set up script
        run: |
          ls
          ./sync-script.sh
