name: Sync Branches

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: Repo3
          repository: muram-105/Repo3

      - name: Run sync script
        run: |
          ./sync-script.sh
