name: Sync Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the first repository
      - name: Checkout Repo3
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo3
          ref: main

      # Checkout the second repository
      - name: Checkout Repo4
        uses: actions/checkout@v2
        with:
          repository: muram-105/Repo4
          ref: main

      # Sync changes from the first repository to the second repository
      - name: Sync Repos
        run: |
          git -C http://github.com/muram-105/Repo4 pull origin main
          git -C Repo4 merge Repo3/main
          git -C Repo4 push origin main
